name: Build

on:
    pull_request:
        types: [opened, edited, synchronize]

jobs:
    setup:
        name: Setup
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
    install:
        name: Installing dependencies
        needs: setup
        runs-on: ubuntu-latest
            - run: npm ci
    lint:
        name: Running linter
        needs: install
        runs-on: ubuntu-latest
            - run: npm run lint:check
    test:
        name: Running tests
        needs: lint
        runs-on: ubuntu-latest
            - run: npm run test
    test:
        name: Creating build
        needs: test
        runs-on: ubuntu-latest
            - run: npm run build:quiet
