name: Create Build

on:
    pull_request:
        types: [opened, edited, synchronize]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@v1
            - name: Set up Node
              uses: actions/setup-node@v1
              with:
                  node-version: 12
            - name: Install dependencies
              run: npm ci
            - name: Linter check
              run: npm run lint:check
            - name: Tests
              run: npm run test
            - name: Build
              run: npm run build:quiet
