name: Release

on:
    pull_request:
        types: closed
        branches:
            - master

jobs:
    publish:
        name: Create release
        if: github.event.pull_request.merged
        runs-on: ubuntu-latest
        steps:
            - name: Set up workflow
              uses: actions/checkout@v1
            - name: Set up Node
              uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org/
            - name: Set up NPM auth
              run: npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            - name: Publish to NPM
              run: npm publish
            - name: Get latest tag
              id: latesttag
              uses: olegtarasov/get-tag@v1
            - name: GitHub release
              uses: marvinpinto/action-automatic-releases@latest
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                automatic_release_tag: ${{ steps.latesttag.outputs.tag }}
                prerelease: false

env:
    NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
