name: Release

on:
    pull_request:
        types: closed
        branches:
            - master

jobs:
    publish-gpr:
        name: Publish to GPR
        if: github.event.pull_request.merged
        runs-on: ubuntu-latest
        steps:
            - name: Set up workflow
              uses: actions/checkout@v2
            - name: Set up Node
              uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://npm.pkg.github.com
                  scope: "@yvesgurcan"
            - name: Set registry
              run: echo registry=https://npm.pkg.github.com/ >> .npmrc
            - name: Publish to GitHub Packages
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

env:
    NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
