name: Release

on:
    pull_request:
        types: [closed]
        branches:
            - master

jobs:
    publish-to-npm:
        name: Publish to NPM
        if: github.event.pull_request.merged
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
              with:
                  ref: master
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org/
            - run: npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            - run: npm publish

    create-release:
        name: Create GitHub release
        if: github.event.pull_request.merged
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
              with:
                  ref: master
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - uses: actions/create-release@v1
              with:
                  tag_name: ${{ github.ref }}
                  release_name: ${{ github.ref }}
                  draft: false
                  prerelease: false

env:
    GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    NPM_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
