name: Version

on: [push]

jobs:
    version-bump:
        name: Version bump
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
              with:
                  ref: master
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org/
            - uses: phips28/gh-action-bump-version@v5.0.16

env:
    NPM_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
